name: test-build
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: Ubuntu Latest
          container: ubuntu:rolling
        - name: Ubuntu 22.04
          container: ubuntu:22.04
        - name: Ubuntu 20.04
          container: ubuntu:20.04
        - name: Ubuntu 18.04
          container: ubuntu:18.04
        - name: Debian Bookworm
          container: debian:12
        - name: Debian Bullseye
          container: debian:11
        - name: Debian Buster
          container: debian:10

    name: ${{matrix.name}}
    runs-on: ubuntu-latest
    container: ${{matrix.container}}

    steps:
      - name: Install dependencies
        # Needed for the docker containers
        run: |
          apt-get update -yq
          DEBIAN_FRONTEND=noninteractive apt-get -yq install software-properties-common git wget ca-certificates
      - name: Checkout GitHub repository
        uses: actions/checkout@v2
      - name: Setup environment
        run: |
          chmod +x gphoto2-updater.sh
          . ./.env
      - name: Build
        run: ./gphoto2-updater.sh --stable
      - name: Check version
        run: |
          gphoto2 --version
          gphoto2 --version | grep -E "^gphoto2\s+$(echo $LATEST_STABLE_GPHOTO_VERSION | sed 's/_/./g')\s"
          gphoto2 --version | grep -E "^libgphoto2\s+$(echo $LATEST_STABLE_LIBGPHOTO_VERSION | sed 's/_/./g')\s"
